<?php
/**
 * Created by PhpStorm.
 * User: AivyYuan
 * Date: 2017/8/16
 * Time: 14:17
 */
namespace app\index\controller;

use app\admin\model\VisitorStats;
use think\Controller;
use think\Session;

class Base extends Controller{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Session::init();
        //更新浏览记录
        $visitor_stats = new VisitorStats();
        $visitor_stats->saveRecord();
    }
}